// src/engine/grid.test.js
//
// Golden-master tests for the extracted grid engine.
//
// The fixtures in __fixtures__/golden-master.json were generated by running the
// ORIGINAL pre-extraction code from useScorecardLogic.js (commit 301f190). These
// tests therefore check that the extracted module in grid.js still produces
// byte-identical grids.
//
// If one of these fails, the grid arithmetic changed. That is not automatically
// wrong -- but it means every saved scorecard will now render differently, so it
// must be a deliberate decision, and the fixtures must be regenerated on purpose.

import fixtures from './__fixtures__/golden-master.json';
import {
    deriveGrid,
    calculateSingleRow,
    createInitialScorecard,
    outcomesFromGrid,
    handsFromGrid,
    findNextAvailableCol,
    TIE,
} from './grid';

// Mirrors the encoding used by the fixture generator: `value` is recoverable
// from `displayValue` plus the column index.
const derivedValue = (colIdx, d) => {
    if (colIdx <= 1) return d;
    if (colIdx === 2) return '';
    if (d === '' || d === 'X') return null;
    return Number(d);
};

describe('golden master: extracted engine matches the original implementation', () => {
    it('has fixtures to check against', () => {
        expect(fixtures.caseCount).toBeGreaterThan(40);
        expect(fixtures.cases).toHaveLength(fixtures.caseCount);
        // The generator found zero cells breaking the value<-displayValue rule,
        // which is what lets these fixtures store displayValue alone.
        expect(fixtures.oddCells).toBe(0);
    });

    fixtures.cases.forEach(({ name, outcomes, numRows, expected }) => {
        describe(name, () => {
            const grid = deriveGrid(outcomes, numRows);

            it('produces the same grid width', () => {
                expect(grid[0].length).toBe(expected.width);
            });

            it('produces the same displayValues', () => {
                const actual = expected.rows.map((_, r) =>
                    grid[r].map((c) => c.displayValue).join(',')
                );
                expect(actual).toEqual(expected.rows);
            });

            it('produces values consistent with those displayValues', () => {
                expected.rows.forEach((row, r) => {
                    row.split(',').forEach((d, c) => {
                        expect(grid[r][c].value).toEqual(derivedValue(c, d));
                    });
                });
            });

            it('leaves cell type and editable untouched', () => {
                grid.forEach((row) => {
                    expect(row[0]).toMatchObject({ type: 'P', editable: true });
                    expect(row[1]).toMatchObject({ type: 'B', editable: true });
                    expect(row[2]).toMatchObject({ type: 'S', editable: false });
                    for (let c = 3; c < row.length; c++) {
                        expect(row[c]).toMatchObject({ type: 'Number', editable: false });
                    }
                });
            });
        });
    });
});

describe('deriveGrid', () => {
    it('does not mutate the grid it starts from', () => {
        const blank = createInitialScorecard(20);
        const snapshot = JSON.stringify(blank);
        calculateSingleRow(blank, 1, 'P', null);
        expect(JSON.stringify(blank)).toBe(snapshot);
    });

    it('is deterministic', () => {
        const outcomes = ['P', 'B', 'B', 'P', 'B', 'P', 'P', 'P'];
        expect(JSON.stringify(deriveGrid(outcomes, 20)))
            .toBe(JSON.stringify(deriveGrid(outcomes, 20)));
    });

    it('round-trips through outcomesFromGrid', () => {
        const outcomes = ['B', 'B', 'P', 'B', 'P', 'P', 'B', 'P', 'P', 'P', 'B'];
        expect(outcomesFromGrid(deriveGrid(outcomes, 30))).toEqual(outcomes);
    });

    it('replaying a prefix matches truncating the full replay', () => {
        // This is the property Phase 1's delete-row fix depends on: a grid is
        // always reproducible from its list of hands.
        const outcomes = ['P', 'P', 'B', 'P', 'B', 'B', 'B', 'P', 'B', 'P'];
        const prefix = deriveGrid(outcomes.slice(0, 6), 20);
        const full = deriveGrid(outcomes, 20);
        for (let r = 0; r <= 6; r++) {
            expect(prefix[r].map((c) => c.displayValue))
                .toEqual(full[r].slice(0, prefix[r].length).map((c) => c.displayValue));
        }
    });
});

describe('documented grid behaviour', () => {
    it('gives every played row both a 1 and a -1', () => {
        const grid = deriveGrid(['P', 'B', 'B', 'P', 'P', 'P', 'B', 'P'], 20);
        for (let r = 1; r <= 8; r++) {
            const shown = grid[r].map((c) => c.displayValue);
            expect(shown).toContain('1');
            expect(shown).toContain('-1');
        }
    });

    it('marks S as R when a hand repeats and O when it switches', () => {
        const grid = deriveGrid(['P', 'P', 'B', 'B', 'P'], 20);
        expect(grid.slice(1, 6).map((r) => r[2].displayValue))
            .toEqual(['O', 'R', 'O', 'R', 'O']);
    });

    it('kills a column permanently once it reaches the X threshold', () => {
        // A long streak drives column 3 down to -4, which then becomes X.
        const grid = deriveGrid(Array(20).fill('P'), 30);
        const col3 = grid.slice(1, 21).map((r) => r[3].displayValue);
        const firstX = col3.indexOf('X');
        expect(firstX).toBeGreaterThan(-1);
        // Every row after the first X stays X -- the column never recovers.
        expect(col3.slice(firstX).every((d) => d === 'X')).toBe(true);
    });

    it('never shows a magnitude above the X threshold', () => {
        const grid = deriveGrid(Array.from({ length: 60 }, (_, i) => (i % 5 === 0 ? 'B' : 'P')), 70);
        grid.forEach((row) => {
            for (let c = 3; c < row.length; c++) {
                if (typeof row[c].value === 'number') {
                    expect(Math.abs(row[c].value)).toBeLessThanOrEqual(4);
                }
            }
        });
    });
});

describe('handsFromGrid', () => {
    it('round-trips a contiguous grid', () => {
        const hands = ['P', 'B', 'B', 'P', 'B', 'P', 'P'];
        expect(handsFromGrid(deriveGrid(hands, 20))).toEqual(hands);
    });

    it('preserves gaps as nulls instead of stopping at them', () => {
        // A grid where row 3 was never played: the user clicked rows 1, 2 and 4.
        const withGap = ['P', 'B', null, 'P'];
        const grid = deriveGrid(withGap, 20);
        expect(handsFromGrid(grid)).toEqual(withGap);
    });

    it('trims trailing blank rows', () => {
        const grid = deriveGrid(['P', 'B'], 50);
        expect(handsFromGrid(grid)).toHaveLength(2);
    });
});

describe('deleting a hand', () => {
    // What the hook does: drop the hand, replay what is left.
    const deleteHand = (grid, rowIdx) => {
        const hands = handsFromGrid(grid);
        const remaining = hands.filter((_, i) => i !== rowIdx - 1);
        return deriveGrid(remaining, grid.length - 1);
    };

    // What the old App.js did: splice the row out of the array and stop.
    const spliceRow = (grid, rowIdx) => grid.filter((_, i) => i !== rowIdx);

    const hands = ['P', 'P', 'B', 'P', 'B', 'B', 'B', 'P', 'P', 'B'];

    it('leaves the grid consistent with the hands that remain', () => {
        const grid = deriveGrid(hands, 30);
        const after = deleteHand(grid, 4);

        const expectedHands = hands.filter((_, i) => i !== 3);
        expect(handsFromGrid(after)).toEqual(expectedHands);

        const rebuilt = deriveGrid(expectedHands, 30);
        expect(after.map((r) => r.map((c) => c.displayValue)))
            .toEqual(rebuilt.map((r) => r.map((c) => c.displayValue)));
    });

    it('keeps the grid the same height', () => {
        const grid = deriveGrid(hands, 30);
        expect(deleteHand(grid, 4)).toHaveLength(grid.length);
        // The old implementation lost a row on every delete.
        expect(spliceRow(grid, 4)).toHaveLength(grid.length - 1);
    });

    it('REGRESSION: the old splice left every row below doing wrong arithmetic', () => {
        const grid = deriveGrid(hands, 30);
        const spliced = spliceRow(grid, 4);

        // Read the hands back out of the spliced grid and replay them. If the
        // splice had been correct, the replay would agree with it.
        const replayed = deriveGrid(handsFromGrid(spliced), spliced.length - 1);

        const splicedRows = spliced.slice(1, 10).map((r) => r.map((c) => c.displayValue).join(','));
        const replayedRows = replayed.slice(1, 10).map((r) => r.map((c) => c.displayValue).join(','));

        expect(splicedRows).not.toEqual(replayedRows);
    });

    it('handles deleting the only hand', () => {
        const grid = deriveGrid(['P'], 20);
        const after = deleteHand(grid, 1);
        expect(handsFromGrid(after)).toEqual([]);
        expect(after[1][0].displayValue).toBe('');
        expect(after[1][1].displayValue).toBe('');
    });

    it('handles deleting the last hand', () => {
        const grid = deriveGrid(hands, 30);
        const after = deleteHand(grid, hands.length);
        expect(handsFromGrid(after)).toEqual(hands.slice(0, -1));
    });

});

describe('findNextAvailableCol', () => {
    it('finds the first unused number column', () => {
        const row = createInitialScorecard(1)[0];
        expect(findNextAvailableCol(row)).toBe(3);
        row[3] = { ...row[3], value: 1, displayValue: '1' };
        expect(findNextAvailableCol(row)).toBe(4);
    });

    it('returns -1 when the row is full', () => {
        const row = createInitialScorecard(1)[0];
        for (let c = 3; c < row.length; c++) {
            row[c] = { ...row[c], value: 1, displayValue: '1' };
        }
        expect(findNextAvailableCol(row)).toBe(-1);
    });
});

describe('ties', () => {
    it('takes a row and marks it T without touching the counts', () => {
        const withTie = deriveGrid(['P', 'B', TIE, 'P'], 20);
        const without = deriveGrid(['P', 'B', 'P'], 20);

        expect(withTie[3][2].displayValue).toBe('T');
        expect(withTie[3][0].displayValue).toBe('');
        expect(withTie[3][1].displayValue).toBe('');
        // The tie row carries no numbers of its own.
        for (let c = 3; c < withTie[3].length; c++) {
            expect(withTie[3][c].displayValue).toBe('');
        }

        // The hand after the tie lands on the numbers it would have had if the
        // tie had never happened.
        expect(withTie[4].slice(3).map((c) => c.displayValue))
            .toEqual(without[3].slice(3).map((c) => c.displayValue));
    });

    it('is not counted as a repeat or a switch', () => {
        // P, tie, P is still a repeat: the tie does not sit between them.
        const grid = deriveGrid(['P', TIE, 'P'], 20);
        expect(grid[3][2].displayValue).toBe('R');

        const chop = deriveGrid(['P', TIE, 'B'], 20);
        expect(chop[3][2].displayValue).toBe('O');
    });

    it('leaves the whole grid identical to the same hands without ties', () => {
        const hands = ['P', 'P', 'B', 'P', 'B', 'B', 'B', 'P', 'P', 'B', 'P'];
        const withTies = ['P', 'P', TIE, 'B', 'P', 'B', TIE, 'B', 'B', 'P', TIE, 'P', 'B', 'P'];

        const a = deriveGrid(hands, 40);
        const b = deriveGrid(withTies, 40);

        const numbersOf = (grid) =>
            grid
                .slice(1)
                .filter((r) => r[2].displayValue !== TIE)
                .map((r) => r.slice(3).map((c) => c.displayValue).join(','))
                .filter((r) => r.replace(/,/g, '') !== '');

        expect(numbersOf(b)).toEqual(numbersOf(a));
    });

    it('round-trips through handsFromGrid', () => {
        const hands = ['P', TIE, 'B', 'B', TIE, 'P'];
        expect(handsFromGrid(deriveGrid(hands, 20))).toEqual(hands);
    });

    it('survives several ties in a row', () => {
        const grid = deriveGrid(['P', TIE, TIE, TIE, 'P'], 20);
        expect(grid[5][2].displayValue).toBe('R');
        expect(handsFromGrid(grid)).toEqual(['P', TIE, TIE, TIE, 'P']);
    });

    it('handles a tie as the very first hand', () => {
        const grid = deriveGrid([TIE, 'P'], 20);
        expect(grid[1][2].displayValue).toBe('T');
        expect(grid[2][2].displayValue).toBe('O');
        expect(handsFromGrid(grid)).toEqual([TIE, 'P']);
    });
});
