// src/engine/grid.test.js
//
// Golden-master tests for the extracted grid engine.
//
// The fixtures in __fixtures__/golden-master.json were generated by running the
// ORIGINAL pre-extraction code from useScorecardLogic.js (commit 301f190). These
// tests therefore check that the extracted module in grid.js still produces
// byte-identical grids.
//
// If one of these fails, the grid arithmetic changed. That is not automatically
// wrong -- but it means every saved scorecard will now render differently, so it
// must be a deliberate decision, and the fixtures must be regenerated on purpose.

import fixtures from './__fixtures__/golden-master.json';
import {
    deriveGrid,
    calculateSingleRow,
    createInitialScorecard,
    outcomesFromGrid,
    findNextAvailableCol,
} from './grid';

// Mirrors the encoding used by the fixture generator: `value` is recoverable
// from `displayValue` plus the column index.
const derivedValue = (colIdx, d) => {
    if (colIdx <= 1) return d;
    if (colIdx === 2) return '';
    if (d === '' || d === 'X') return null;
    return Number(d);
};

describe('golden master: extracted engine matches the original implementation', () => {
    it('has fixtures to check against', () => {
        expect(fixtures.caseCount).toBeGreaterThan(40);
        expect(fixtures.cases).toHaveLength(fixtures.caseCount);
        // The generator found zero cells breaking the value<-displayValue rule,
        // which is what lets these fixtures store displayValue alone.
        expect(fixtures.oddCells).toBe(0);
    });

    fixtures.cases.forEach(({ name, outcomes, numRows, expected }) => {
        describe(name, () => {
            const grid = deriveGrid(outcomes, numRows);

            it('produces the same grid width', () => {
                expect(grid[0].length).toBe(expected.width);
            });

            it('produces the same displayValues', () => {
                const actual = expected.rows.map((_, r) =>
                    grid[r].map((c) => c.displayValue).join(',')
                );
                expect(actual).toEqual(expected.rows);
            });

            it('produces values consistent with those displayValues', () => {
                expected.rows.forEach((row, r) => {
                    row.split(',').forEach((d, c) => {
                        expect(grid[r][c].value).toEqual(derivedValue(c, d));
                    });
                });
            });

            it('leaves cell type and editable untouched', () => {
                grid.forEach((row) => {
                    expect(row[0]).toMatchObject({ type: 'P', editable: true });
                    expect(row[1]).toMatchObject({ type: 'B', editable: true });
                    expect(row[2]).toMatchObject({ type: 'S', editable: false });
                    for (let c = 3; c < row.length; c++) {
                        expect(row[c]).toMatchObject({ type: 'Number', editable: false });
                    }
                });
            });
        });
    });
});

describe('deriveGrid', () => {
    it('does not mutate the grid it starts from', () => {
        const blank = createInitialScorecard(20);
        const snapshot = JSON.stringify(blank);
        calculateSingleRow(blank, 1, 'P', null);
        expect(JSON.stringify(blank)).toBe(snapshot);
    });

    it('is deterministic', () => {
        const outcomes = ['P', 'B', 'B', 'P', 'B', 'P', 'P', 'P'];
        expect(JSON.stringify(deriveGrid(outcomes, 20)))
            .toBe(JSON.stringify(deriveGrid(outcomes, 20)));
    });

    it('round-trips through outcomesFromGrid', () => {
        const outcomes = ['B', 'B', 'P', 'B', 'P', 'P', 'B', 'P', 'P', 'P', 'B'];
        expect(outcomesFromGrid(deriveGrid(outcomes, 30))).toEqual(outcomes);
    });

    it('replaying a prefix matches truncating the full replay', () => {
        // This is the property Phase 1's delete-row fix depends on: a grid is
        // always reproducible from its list of hands.
        const outcomes = ['P', 'P', 'B', 'P', 'B', 'B', 'B', 'P', 'B', 'P'];
        const prefix = deriveGrid(outcomes.slice(0, 6), 20);
        const full = deriveGrid(outcomes, 20);
        for (let r = 0; r <= 6; r++) {
            expect(prefix[r].map((c) => c.displayValue))
                .toEqual(full[r].slice(0, prefix[r].length).map((c) => c.displayValue));
        }
    });
});

describe('documented grid behaviour', () => {
    it('gives every played row both a 1 and a -1', () => {
        const grid = deriveGrid(['P', 'B', 'B', 'P', 'P', 'P', 'B', 'P'], 20);
        for (let r = 1; r <= 8; r++) {
            const shown = grid[r].map((c) => c.displayValue);
            expect(shown).toContain('1');
            expect(shown).toContain('-1');
        }
    });

    it('marks S as R when a hand repeats and O when it switches', () => {
        const grid = deriveGrid(['P', 'P', 'B', 'B', 'P'], 20);
        expect(grid.slice(1, 6).map((r) => r[2].displayValue))
            .toEqual(['O', 'R', 'O', 'R', 'O']);
    });

    it('kills a column permanently once it reaches the X threshold', () => {
        // A long streak drives column 3 down to -4, which then becomes X.
        const grid = deriveGrid(Array(20).fill('P'), 30);
        const col3 = grid.slice(1, 21).map((r) => r[3].displayValue);
        const firstX = col3.indexOf('X');
        expect(firstX).toBeGreaterThan(-1);
        // Every row after the first X stays X -- the column never recovers.
        expect(col3.slice(firstX).every((d) => d === 'X')).toBe(true);
    });

    it('never shows a magnitude above the X threshold', () => {
        const grid = deriveGrid(Array.from({ length: 60 }, (_, i) => (i % 5 === 0 ? 'B' : 'P')), 70);
        grid.forEach((row) => {
            for (let c = 3; c < row.length; c++) {
                if (typeof row[c].value === 'number') {
                    expect(Math.abs(row[c].value)).toBeLessThanOrEqual(4);
                }
            }
        });
    });
});

describe('findNextAvailableCol', () => {
    it('finds the first unused number column', () => {
        const row = createInitialScorecard(1)[0];
        expect(findNextAvailableCol(row)).toBe(3);
        row[3] = { ...row[3], value: 1, displayValue: '1' };
        expect(findNextAvailableCol(row)).toBe(4);
    });

    it('returns -1 when the row is full', () => {
        const row = createInitialScorecard(1)[0];
        for (let c = 3; c < row.length; c++) {
            row[c] = { ...row[c], value: 1, displayValue: '1' };
        }
        expect(findNextAvailableCol(row)).toBe(-1);
    });
});

